import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { once } from 'node:events';
import { chromium } from 'playwright-core';
import { createServer } from '../server/index.js';
import { Game } from '../server/game.js';

const executablePath = process.env.JANGGI_BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
test('실제 브라우저 Worker 장기 분석·취소·착수 충돌·복기', { skip: !existsSync(executablePath), timeout: 60000 }, async t => {
  const game = new Game();
  const server = createServer({ game });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(() => { server.closeAllConnections(); server.close(); });
  const browser = await chromium.launch({ executablePath, headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  page.on('console', message => { if (message.type() === 'error') console.log('Browser error:', message.text()); });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let serverRecommendations = 0;
  page.on('request', request => { if (request.url().endsWith('/api/recommend')) serverRecommendations++; });
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.waitForFunction(() => !document.getElementById('recommend').disabled);
  await page.click('#recommend');
  await page.waitForFunction(() => document.getElementById('advice').textContent.startsWith('추천:') || document.getElementById('error').textContent, null, { timeout: 25000 });
  assert.equal(await page.locator('#error').textContent(), '');
  console.log('Browser measurement:', await page.locator('#advice').textContent());
  assert.equal(serverRecommendations, 0);
  await page.click('#recommend');
  await page.click('#cancel-analysis');
  assert.match(await page.locator('#advice').textContent(), /취소/);
  await page.click('#recommend');
  await game.act('move', { move: 'a4b4', revision: game.revision });
  await page.waitForFunction(() => document.getElementById('status').textContent.includes('1수'));
  assert.equal(await page.locator('.suggested').count(), 0);
  await page.click('#review-first');
  await page.waitForFunction(() => document.getElementById('status').textContent.includes('복기 0/1'));
  assert.equal(await page.locator('#recommend').isDisabled(), true);
  await page.click('#review-live');
  await page.click('#recommend');
  await page.waitForFunction(() => document.getElementById('advice').textContent.startsWith('추천:') || document.getElementById('error').textContent);
  assert.equal(await page.locator('#error').textContent(), '');
  assert.deepEqual(game.moves, ['a4b4']);
  assert.deepEqual(errors, []);
});
